# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Dawah Nation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: Dawah-Nation

    steps:
    - uses: actions/checkout@v3
    - name: Build yourself
      run: in Dawah Nation -v
    - name: Run tests
      run: Dawah test -v
